"use strict";

export const uiState = {
  state: null,
  welcomeModalVisible: false,
  newRunModalVisible: false,
  newRunLoading: false,
  settingsMenuOpen: false,
  runCycleId: 0,
  dayCycleKey: null,
  dayCycleProgress: 0,
  dayCycleTimer: null,
  dayCycleLastTick: null,
  dayCycleAdvancing: false,
  dayDecisionThresholds: [],
  pendingAdvanceState: null,
  modalVisible: false,
  summaryAnimationKey: null,
  pendingChoice: null,
  devPanelCollapsed: false,
  devInstantProgression: false,
  devShowDiagnostics: false,
  devStrategy: "echo",
  devRequestInFlight: false,
};
